#!/usr/bin/expect

set timeout -1

spawn /tmp/burpsuite.sh -f readline

expect "This will install Burp Suite Community Edition on your computer."
send "\r"

expect "Where should Burp Suite Community Edition be installed?"
send "\r"

expect "Create symlinks?"
send "\r"

expect "Select the folder where you would like Burp Suite Community Edition to create symlinks, then click Next."
send "\r"

# done
expect eof
